name: quran_tv
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  json_annotation: ^4.9.0
  go_router: ^16.1.0
  equatable: ^2.0.7
  flutter_svg: ^2.2.0
  flutter_sound: ^9.28.0
  audio_session: ^0.2.2
  path: ^1.9.1
  firebase_core: ^4.0.0
  googleapis_auth: ^2.0.0
  http: ^1.5.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.10.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/reciters/
    - assets/raw/
    - assets/quran/al-mulk/
    - assets/bucket/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #