// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ_mOLEn9MWXsWKgXNDbec4PL-MS8gS98',
    appId: '1:939487481535:web:a67cd64a5c1b639339400a',
    messagingSenderId: '939487481535',
    projectId: 'qurantv-ac735',
    authDomain: 'qurantv-ac735.firebaseapp.com',
    storageBucket: 'qurantv-ac735.firebasestorage.app',
    measurementId: 'G-YK90B5XJZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtwQVdgjUBGB9NXzWv6ovGbYjOJjydf5Y',
    appId: '1:939487481535:android:b4037e71ac2ab05c39400a',
    messagingSenderId: '939487481535',
    projectId: 'qurantv-ac735',
    storageBucket: 'qurantv-ac735.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcwvB4sPOgZrdENWEFK0P37jHJ1WtqT6U',
    appId: '1:939487481535:ios:0c80d7da5bac30fc39400a',
    messagingSenderId: '939487481535',
    projectId: 'qurantv-ac735',
    storageBucket: 'qurantv-ac735.firebasestorage.app',
    iosBundleId: 'com.example.quranTv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcwvB4sPOgZrdENWEFK0P37jHJ1WtqT6U',
    appId: '1:939487481535:ios:0c80d7da5bac30fc39400a',
    messagingSenderId: '939487481535',
    projectId: 'qurantv-ac735',
    storageBucket: 'qurantv-ac735.firebasestorage.app',
    iosBundleId: 'com.example.quranTv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ_mOLEn9MWXsWKgXNDbec4PL-MS8gS98',
    appId: '1:939487481535:web:0ba1dc75afa413ce39400a',
    messagingSenderId: '939487481535',
    projectId: 'qurantv-ac735',
    authDomain: 'qurantv-ac735.firebaseapp.com',
    storageBucket: 'qurantv-ac735.firebasestorage.app',
    measurementId: 'G-9LGP962G5Y',
  );
}
